import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        style={{ maxWidth: 430, margin: '0 auto', background: '#fff' }}
      >
        <div style={{ minHeight: '100vh', paddingBottom: 72 }}>
          {children}
        </div>
        {/* Bottom Nav Bar */}
        <nav
          className="fixed bottom-0 left-0 right-0 z-50 border-t border-gray-100 bg-white"
          style={{ maxWidth: 430, margin: '0 auto', height: 64 }}
        >
          <div className="flex justify-between items-center h-full px-2" style={{ height: 64 }}>
            <a href="/dashboard" className="flex flex-col items-center flex-1 py-2 text-black hover:text-blue-600 transition-colors">
              <svg width="24" height="24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" className="mb-1"><path d="M3 12l9-9 9 9"/><path d="M9 21V9h6v12"/></svg>
              <span className="text-xs font-medium">Home</span>
            </a>
            <a href="/ai-chat" className="flex flex-col items-center flex-1 py-2 text-black hover:text-blue-600 transition-colors">
              <svg width="24" height="24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" className="mb-1"><circle cx="12" cy="12" r="10"/><path d="M8 15s1.5-2 4-2 4 2 4 2"/><path d="M9 9h.01"/><path d="M15 9h.01"/></svg>
              <span className="text-xs font-medium">AI</span>
            </a>
            <a href="/services" className="flex flex-col items-center flex-1 py-2 text-black hover:text-blue-600 transition-colors">
              <svg width="24" height="24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" className="mb-1"><rect x="3" y="7" width="18" height="13" rx="2"/><path d="M16 3v4"/><path d="M8 3v4"/></svg>
              <span className="text-xs font-medium">Services</span>
            </a>
            <a href="/profile" className="flex flex-col items-center flex-1 py-2 text-black hover:text-blue-600 transition-colors">
              <svg width="24" height="24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" className="mb-1"><circle cx="12" cy="8" r="4"/><path d="M4 20c0-2.2 3.6-4 8-4s8 1.8 8 4"/></svg>
              <span className="text-xs font-medium">Profile</span>
            </a>
          </div>
        </nav>
      </body>
    </html>
  );
}
